/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

class App {
    String getGreeting() {
        return "Hello World!";
    }

    void main() {
        System.out.println(getGreeting());
    }
}
